### ISSUE TITLE
problem when call the function blockNormalSystolicMultiply to compute matrix multiplication

### ISSUE THREAD

**Issue by ShirleyGuo** [SachinKonan/MorphableSystolicArrayDesign#1]
I have encountered some strange results when I call the funciton:
 result, iterations, clks, for_freq, time = blockNormalSystolicMultiply(initNormalSystolic(x, 1), A, B, verbose = False)
for example, when I set A and B to be 1x1 matrix, the clks is 5 but isn't it strange to take 5 clks to compute one multiplication?
also, I wonder if the second parameter of initNormalSystolic has to be 1, as I see in all the examples that this parameter is always 1. when I change this parameter to be not 1, for example, I set  initNormalSystolic(32,32), I suppose that this is a 32x32 systolic array, and I set A and B be 100x100 matrices. but the blockNormalSystolicMultiply function throws out the error infomation as follows:
  File "testnormalblocksys.py", line 18, in <module>
    result, iterations, clks, for_freq, time = blockNormalSystolicMultiply(initNormalSystolic(32, 32), A, B, verbose = False)
  File "D:\MorphableSystolicArrayDesign-master\libs.py", line 229, in blockNormalSystolicMultiply
    out[rstart:rend, 0:] = out[rstart:rend, 0:] + m[0:rend - rstart, :] 
ValueError: operands could not be broadcast together with shapes (32,100) (32,32)

I hope that you can give me some insights about this problem.

**Comment by SachinKonan** [comment]
Hi, so in regards to your first question, what was the size of x? Because if the size of x exceeds that of the matrices you intend to multiply, the library automatically pads the arrays to fit the systolic array, which will increase the number of clock cycles. For your second question, the "blockNormalSystolicMuliply" function is generally made to handle 1D systolic arrays, however, in order for a 2D operation like you are trying to do, I added a new function called "blockSystolicMultiply2D" in the backstaticsys.py file in the Normal Systolic Directory (NormalSystolic/backstaticsys.py). Let me know if this solves your issue.

**Comment by ShirleyGuo** [comment]
Is the NormalSystolic/backstaticsys.py implement the systolic array as follows?
Activations flow from left pe to right pe, weights flow from top pe to bottom pe and the partial sum is stored in each pe.
And I don't really figure out how you simulate the hardware behavior of getting the partial sum out of the pe in the corresponding cycle.

**Comment by SachinKonan** [comment]
yes it does implement that type of flow, you can see that if you look at the backrunSystolic() method. It follows the methodology as seen here: http://web.cecs.pdx.edu/~mperkows/temp/May22/0020.Matrix-multiplication-systolic.pdf. The hardware behavior of retrieving the partial sum from each PE after matrix multiplication isnt simulated, only the matrix multiplication **process** is simulated, since that was most crucial for optimization.

**Comment by ShirleyGuo** [comment]
for the first question, A and B are 1x1 matrices and array is 3x1 but clks is 5 when calling blockNormalSystolicMultiply
[
A = np.random.randint(low = 0, high = 10, size = (1,1))
B = np.random.randint(low = 0, high = 10, size = (1,1))
print(A,B)
res, its, clks, for_freq, t = blockNormalSystolicMultiply(initNormalSystolic(3,1), A, B, False)
print(res,its,clks)
]
[
[[4]] [[4]]
[[16.]] 1 5
]

A and B are 1x1 matrices and array is 3x1 but clks is 3 when calling the new function blockSystolicMultiply2D.
[
a = np.random.randint(low = 0, high = 10, size = (1,1))
b = np.random.randint(low = 0, high = 10, size = (1,1))
sys = initSystolic(3, 1)
out,blockiterations, clocks = blockSystolicMultiply2D(sys, a, b, verbose = False)
print('blockits:',blockiterations,'clks:',clocks)
]
[
blockits: 1 clks: 3
]

is this because the padding strategy is different?

**Comment by SachinKonan** [comment]
sr - systolic row size, sc - systolic column size.
sr,sc - 3,1 for this case

yes, in the NormalSystolic Method, the A matrix is padded to be of size (sr, sr) and the B vector is padded to be of size (sr, sc) -- sc is 1, because this meant to be for 1-D systolic operations. So in your 2, 1x1 matrix multiplication, the first matrix is padded to be of size 3,3, while the second is padded to be of size 3x1. This causes the clock ticks to be 5. In the 2D method, the A matrix to be of size (sr, sc), and the B vector is to be padded to be of size (sc, sc). A will be padded to size 3x1, while B vector to size 1x1. The clock ticks of this will end up being 3, simply because it takes 3 cycles for the B element to travel down 3 systolic processing elements. Either strategy is valid, since the end result of the multiplication of matrices of size (sr, sr) & (sr, sc) or (sr,sc) & (sc,sc) is still (sr,sc). The first padding strategy was utilized because it necessary for the first matrix to be square and the second to be a vector. In general to blockSystolic2D() method has a more general padding method.
